name: fl_danmaku_example
description: "example for fl_danmaku_widget"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  fl_danmaku_widget:
    path: ../
  google_fonts: ^6.2.1
  file_picker: ^10.0.0
  xml: ^6.5.0
  platform_info: ^5.0.0
  flutter_acrylic: ^1.1.0
  flutter_font_picker: ^1.4.0

dependency_overrides:
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  names_launcher: ^0.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/

names_launcher:
  name:
   default: "fl_danmaku_example"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true